create or replace procedure SP_GET_SYSTEMS
( P_DNI IN VARCHAR2,
  P_cursor OUT NOCOPY SYS_REFCURSOR
)
as
  V_DNI VARCHAR2(8);
begin
  V_DNI:=P_DNI;

/*=====================================================================
=====Se va listar los sistemas de un Usuario a partir de su DNI========
=====================================================================*/
  open P_cursor for
--SIR
SELECT 
S.CO_EMPL AS CO_EMPL,
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR LIMA' AS SISTEMA,
'SIR_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )

--
UNION
SELECT 
S.CO_EMPL AS CO_EMPL,
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR CALLAO' AS SISTEMA ,
'SIR_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL@DBL_0102_UNICA  S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )
--
UNION
SELECT 
S.CO_EMPL AS CO_EMPL,
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR HUARAL' AS SISTEMA ,
'SIR_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL@DBL_0103_UNICA  S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
S.CO_EMPL AS CO_EMPL,
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR HUACHO' AS SISTEMA ,
'SIR_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL@DBL_0104_UNICA  S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
S.CO_EMPL AS CO_EMPL,    
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR CAÑETE' AS SISTEMA ,
'SIR_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL@DBL_0105_UNICA  S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
S.CO_EMPL AS CO_EMPL,
S.CO_USUA AS ID_USER,
S.IN_ESTD AS IN_ESTD,
'SIR BARRANCA' AS SISTEMA ,
'SIR_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL@DBL_0106_UNICA  S
WHERE ( S."DNI"= V_DNI ) AND
( S.IN_ESTD IN ('I', 'A') )

--RPV
UNION
SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,        
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV LIMA'  AS SISTEMA,
'RPV_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )

--
UNION
SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,                 
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV CALLAO'  AS SISTEMA,
'RPV_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"@DBL_0102_UNICA
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )

--
UNION
SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,                 
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV HUARAL'  AS SISTEMA,
'RPV_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"@DBL_0103_UNICA
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )

UNION

SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,                
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV HUACHO'  AS SISTEMA,
'RPV_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"@DBL_0104_UNICA
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )

UNION

SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV CAÑETE'  AS SISTEMA,
'RPV_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"@DBL_0105_UNICA
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )

UNION

SELECT     
"RPV"."TA_EMPL"."CO_EMPL" AS CO_EMPL,    
"RPV"."TA_EMPL"."ID_USER" AS ID_USER,
"RPV"."TA_EMPL"."IN_ESTD" AS IN_ESTD,
'RPV BARRANCA'  AS SISTEMA,
'RPV_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM "RPV"."TA_EMPL"@DBL_0106_UNICA
WHERE ( RPV."TA_EMPL"."DNI"= V_DNI ) AND
( IN_ESTD  IN ('I','A')  )


--PERMISOS
UNION 
SELECT     
T.C_C_CODIGO AS CO_EMPL,
PT.CO_USUA AS ID_USER,
CASE
WHEN PT.IN_ESTD ='01'
THEN 'A'
WHEN PT.IN_ESTD = '02'
THEN 'I'
END AS IN_ESTD,
'PERMISOS'  AS SISTEMA,
'PERMISOS' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM SIGARP.PERM_TA_USUA PT ,SIGARP.TRABAJADOR T
WHERE ( TRIM(T.C_C_CODIGO) = TRIM(PT.CO_EMPL) ) AND
T.C_C_LIB_ELECTORAL=V_DNI

--CONSULTA REGISTRAL LIMA
UNION
SELECT 
C.CO_EMPL AS CO_EMPL, 
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG LIMA'  AS SISTEMA,
'CONSULTA_REG_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0101_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0101_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0101_UNICA
WHERE  DNI=V_DNI)

UNION
SELECT 
C.CO_EMPL AS CO_EMPL, 
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG. CALLAO'  AS SISTEMA,
'CONSULTA_REG_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0102_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0102_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0102_UNICA
WHERE  DNI=V_DNI)
UNION
SELECT 
C.CO_EMPL AS CO_EMPL, 
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG. HUARAL'  AS SISTEMA,
'CONSULTA_REG_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0103_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0103_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0103_UNICA
WHERE  DNI=V_DNI)
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG. HUACHO'  AS SISTEMA,
'CONSULTA_REG_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0104_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0104_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0104_UNICA
WHERE  DNI=V_DNI)
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG. CAÑETE'  AS SISTEMA,
'CONSULTA_REG_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0105_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0105_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0105_UNICA
WHERE  DNI=V_DNI)
UNION  
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'CONSULTA REG. BARRANCA'  AS SISTEMA,
'CONSULTA_REG_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM orlcdba.tp_empl_vpb@DBL_0106_UNICA C
WHERE IN_ESTD IN ('A','I') 
AND CO_EMPL IN 
(SELECT CO_EMPL--,CO_USUA,IN_ESTD ,T.AP_PATE_EMPL,T.NO_EMPL
FROM orlcdba.tp_empl@DBL_0106_UNICA T
WHERE  DNI=V_DNI 
UNION
SELECT CO_EMPL
FROM RPV.TA_EMPL@DBL_0106_UNICA
WHERE  DNI=V_DNI)


--MESA DE PARTES
UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-LIMA' AS SISTEMA,
'MESA_DE_PARTES-LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0101_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0101_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0101_UNICA WHERE DNI=V_DNI
)
--

UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-CALLAO' AS SISTEMA,
'MESA_DE_PARTES-CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0102_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0102_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0102_UNICA WHERE DNI=V_DNI
)
--
UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-HUARAL' AS SISTEMA,
'MESA_DE_PARTES-HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0103_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0103_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0103_UNICA WHERE DNI=V_DNI
)
--
UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-HUACHO' AS SISTEMA,
'MESA_DE_PARTES-HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0104_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0104_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0104_UNICA WHERE DNI=V_DNI
)
--
UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-CAÑETE' AS SISTEMA,
'MESA_DE_PARTES-CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0105_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0105_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0105_UNICA WHERE DNI=V_DNI
)
--
UNION
SELECT C.CO_USUA  AS CO_EMPL,
TU.ID_USUA  AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'MESA DE PARTES-BARRANCA' AS SISTEMA,
'MESA_DE_PARTES-BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL 
FROM ORLCDBA.TR_PERF_USUA@DBL_0106_UNICA C INNER JOIN  ORLCDBA.TP_USUA@DBL_0106_UNICA TU
ON C.CO_USUA  = TU.CO_USUA
WHERE C.CO_PERF='0096' 
AND C.IN_ESTD IN ('A','I') 
AND TU.CO_EMPL IN(
SELECT  CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0106_UNICA WHERE DNI=V_DNI
)


--ORIENTACION
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION LIMA'  AS SISTEMA,
'ORIENTACION_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION LIMA'  AS SISTEMA,
'ORIENTACION_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0101_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0101_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI

--
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION CALLAO'  AS SISTEMA,
'ORIENTACION_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0102_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0102_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION CALLAO'  AS SISTEMA,
'ORIENTACION_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0102_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0102_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
--
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION HUARAL'  AS SISTEMA,
'ORIENTACION_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0103_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0103_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION HUARAL'  AS SISTEMA,
'ORIENTACION_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0103_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0103_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
--
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION HUACHO'  AS SISTEMA,
'ORIENTACION_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0104_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0104_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION HUACHO'  AS SISTEMA,
'ORIENTACION_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0104_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0104_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
--
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION CAÑETE'  AS SISTEMA,
'ORIENTACION_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0105_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0105_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION CAÑETE'  AS SISTEMA,
'ORIENTACION_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0105_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0105_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
--
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION BARRANCA'  AS SISTEMA,
'ORIENTACION_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0106_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0106_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.ID_USER AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'ORIENTACION BARRANCA'  AS SISTEMA,
'ORIENTACION_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM ORLCDBA.TP_ESTA_ORIE_EMPL@DBL_0106_UNICA C
INNER JOIN RPV.TA_EMPL@DBL_0106_UNICA  T 
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI


--SIGESAR
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR LIMA'  AS SISTEMA,
'SIGESAR_LIMA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI

UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR CALLAO'  AS SISTEMA,
'SIGESAR_CALLAO' AS VALOR,
'@DBL_0102_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0102_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0102_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR HUARAL'  AS SISTEMA,
'SIGESAR_HUARAL' AS VALOR,
'@DBL_0103_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0103_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0103_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR HUACHO'  AS SISTEMA,
'SIGESAR_HUACHO' AS VALOR,
'@DBL_0104_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0104_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0104_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR CAÑETE'  AS SISTEMA,
'SIGESAR_CANETE' AS VALOR,
'@DBL_0105_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0105_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0105_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD,
'SIGESAR BARRANCA'  AS SISTEMA,
'SIGESAR_BARRANCA' AS VALOR,
'@DBL_0106_UNICA'  AS DBL
FROM ARCHIVO.TECNICO@DBL_0106_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0106_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND T.IN_ESTD IN ('I', 'A') AND T.DNI=V_DNI


--FICHAS GPI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'REGISTRO DE FICHA'  AS SISTEMA,
'REGISTRO_DE_FICHA' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_FICH_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND C.CO_MODU='01' 
AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'TITULOS DE MINERIA'  AS SISTEMA,
'TITULOS_DE_MINERIA'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_FICH_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND C.CO_MODU='02' 
AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'LIBRO DIARIO'  AS SISTEMA,
'LIBRO_DIARIO'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_FICH_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND C.CO_MODU='03' 
AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'REGISTRO DE FICHA PJ'  AS SISTEMA,
'REGISTRO_DE_FICHA_PJ'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_FICH_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND C.CO_MODU='04' 
AND T.DNI=V_DNI
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
CASE
WHEN C.IN_ESTD ='1'
THEN 'A'
WHEN C.IN_ESTD = '0'
THEN 'I'
END AS IN_ESTD,
'REGISTRO DE FICHA PN'  AS SISTEMA,
'REGISTRO_DE_FICHA_PN'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_FICH_EMPL@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.CO_EMPL= T.CO_EMPL 
AND C.CO_MODU='05' 
AND T.DNI=V_DNI


--SARP
UNION
SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-CALLAO' AS SISTEMA ,
'SARP_CALLAO'  AS VALOR,
'@DBL_RPU_CALLAO'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_CALLAO EC,
RPUDBA.TP_USUA@DBL_RPU_CALLAO UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     ( UC.NU_DOCU_IDEN=V_DNI ) AND
( UC.IN_ESTD IN ('I', 'A') )

UNION

SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-CAÑETE' AS SISTEMA,
'SARP_CANETE'  AS VALOR,
'@DBL_RPU_CANETE'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_CANETE EC,
RPUDBA.TP_USUA@DBL_RPU_CANETE UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )

UNION

SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-HUACHO' AS SISTEMA,
'SARP_HUACHO'  AS VALOR,
'@DBL_RPU_HUACHO'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_HUACHO EC,
RPUDBA.TP_USUA@DBL_RPU_HUACHO UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )

UNION

SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-BARRANCA' AS SISTEMA,
'SARP_BARRANCA'  AS VALOR,
'@DBL_BARRANCA_RPU'  AS  DBL
FROM   RPUDBA.TA_EMPL@DBL_BARRANCA_RPU EC,
RPUDBA.TP_USUA@DBL_BARRANCA_RPU UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-HUARAL' AS SISTEMA,
'SARP_HUARAL'  AS VALOR,
'@DBL_HUARAL_RPU'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_HUARAL_RPU EC,
RPUDBA.TP_USUA@DBL_HUARAL_RPU UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-ESTE' AS SISTEMA,
'SARP_ESTE'  AS VALOR,
'@DBL_RPU_ESTE'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_ESTE EC,
RPUDBA.TP_USUA@DBL_RPU_ESTE UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-NORTE' AS SISTEMA,
'SARP_NORTE'  AS VALOR,
'@DBL_RPU_NORTE'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_NORTE EC,
RPUDBA.TP_USUA@DBL_RPU_NORTE UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )
UNION
SELECT 
EC.CO_EMPL AS CO_EMPL,
UC.ID_USUA AS ID_USER,
UC.IN_ESTD AS IN_ESTD,
'SARP-SUR' AS SISTEMA,
'SARP_SUR'  AS VALOR,
'@DBL_RPU_SUR'  AS DBL
FROM   RPUDBA.TA_EMPL@DBL_RPU_SUR EC,
RPUDBA.TP_USUA@DBL_RPU_SUR UC
WHERE EC.CO_EMPL = UC.CO_EMPL
AND     (  UC.NU_DOCU_IDEN=V_DNI  ) AND
( UC.IN_ESTD IN ('I', 'A') )

-- SIDUREG
UNION
SELECT C.ID_USUA AS CO_EMPL,
T.CO_USUA AS ID_USER,
C.IN_ESTD,
'SIDUREG LIMA'  AS SISTEMA,
'SIDUREG_LIMA'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM RECPART.TA_USUA@DBL_0101_UNICA C
INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
ON C.ID_USUA= T.CO_EMPL 
AND T.DNI=V_DNI

--DOCFLOW
UNION
SELECT 
C.CO_EMPL AS CO_EMPL,
C.ID_USUA AS ID_USER,
C.IN_ESTD AS IN_ESTD,
'DOCFLOW' AS SISTEMA,
'DOCFLOW' AS VALOR,
'@DBL_RPU_NORTE'  AS DBL
FROM SOPORTE.TP_EMPL@DBL_RPU_NORTE C
WHERE C.IN_ESTD IN ('A','I') AND
TRIM(C.CO_EMPL) IN
(SELECT TRIM(C_C_CODIGO) FROM SIGARP.TRABAJADOR@DBL_0101_UNICA WHERE C_C_LIB_ELECTORAL=V_DNI
UNION
SELECT TRIM(CO_EMPL) FROM ORLCDBA.TP_EMPL@DBL_0101_UNICA WHERE DNI=V_DNI
) 

--ORICON
UNION
SELECT 'ORICO' AS CO_EMPL,
TRIM(C.ID_USER) AS ID_USER,
C.ID_ESTD AS IN_ESTD,
'ORICON'  AS SISTEMA,
'ORICON'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM INTRANET.TP_ORICON_EMPL@DBL_0101_UNICA C
--INNER JOIN ORLCDBA.TP_EMPL@DBL_0101_UNICA T
--ON TRIM(C.CO_USER)= TRIM(T.DNI)
WHERE C.ID_ESTD IN ('I', 'A') 
AND TRIM(C.CO_USER)=TRIM(V_DNI)

--SIGARP
UNION
SELECT 
(SELECT C_C_CODIGO FROM SIGARP.TRABAJADOR WHERE C_C_LIB_ELECTORAL=V_DNI 
AND C_C_SITUACION_TRAB='01' AND D_CESE IS NULL) AS CO_EMPL,
TR.C_C_USUARIO AS ID_USER,
CASE
WHEN TR.C_FL_ESTADO ='1'
THEN 'A'
WHEN TR.C_FL_ESTADO = '2'
THEN 'I'
END AS IN_ESTD,
'SIGARP' AS SISTEMA,
'SIGARP' AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM SIGARP.USUARIO@DBL_0101_UNICA TR  
WHERE C_C_USUARIO IN
(SELECT C_C_USUARIO FROM SIGARP.USUARIO_TRABAJADOR UTI
WHERE C_C_CODIGO IN
(SELECT C_C_CODIGO FROM SIGARP.TRABAJADOR TRA
WHERE C_C_LIB_ELECTORAL=V_DNI AND 
TRA.C_C_SITUACION_TRAB='01' AND TRA.D_CESE IS NULL
)
)

--SIR MINERIA
UNION
SELECT
C.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
C.IN_ESTD  AS IN_ESTD,
'SIR MINERIA'  AS SISTEMA,
'SIR_MINERIA'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL 
FROM ORLCDBA.TA_EMPL_SECC C INNER JOIN 
orlcdba.tp_empl@DBL_0101_UNICA T 
ON  C.CO_EMPL = T.CO_EMPL
WHERE C.CO_AREA IN ('21100','21103','21109','21104')--SECC MINERIA
AND C.IN_ESTD IN ('A','I') AND
T.DNI=V_DNI

--TRIBUNAL REGISTRAL
UNION
SELECT 
TR.CO_EMPL AS CO_EMPL,
T.CO_USUA AS ID_USER,
TR.IN_ESTD  AS IN_ESTD,
'TRIBUNAL REG. LIMA'  AS SISTEMA,
'TRIBUNAL_REG_LIMA'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL_TRIB@DBL_0101_UNICA TR INNER JOIN 
orlcdba.tp_empl@DBL_0101_UNICA T 
ON  TR.CO_EMPL = T.CO_EMPL
WHERE TR.IN_ESTD IN ('A','I') AND
T.DNI=V_DNI 

--GESTION GERENCIAL
UNION
SELECT 
TR.CO_EMPL AS CO_EMPL,
TR.ID_EMPL AS ID_USER,
TR.IN_ESTD  AS IN_ESTD,
'GEST. GERENCIAL LIMA'  AS SISTEMA,
'GEST_GERENCIAL_LIMA'  AS VALOR,
'@DBL_0101_UNICA'  AS DBL
FROM ORLCDBA.TP_EMPL_INTRA@DBL_0101_UNICA TR    
WHERE TR.IN_ESTD IN ('A','I') AND
TR.CO_EMPL IN
(SELECT CO_EMPL FROM ORLCDBA.TP_EMPL@DBL_0101_UNICA WHERE DNI =V_DNI
)
;

END;
